link_tutorial_home: https://www.railstutorial.org/
link_tutorial_help: https://www.railstutorial.org/help
link_tutorial_book: https://www.railstutorial.org/book
link_learn: https://www.learnenough.com/
link_screencasts: https://screencasts.railstutorial.org/
link_ruby_on_rails: https://rubyonrails.org/
