link_tutorial_home: https://www.railstutorial.org/
link_tutorial_help: https://www.railstutorial.org/help
link_tutorial_book: https://www.railstutorial.org/book
link_learn: https://www.learnenough.com/
link_screencasts: https://screencasts.railstutorial.org/
link_ruby_on_rails: https://rubyonrails.org/
link_michael: http://www.michaelhartl.com/
link_tutorial_news: http://news.railstutorial.org/
link_tutorial_contact: "https://www.railstutorial.org/contact"
max_name: 50
max_email: 255
min_pass: 6
valid_email_regex: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i'
